version: '3'
services:
  db:
    image: mysql:5.7
    hostname: rails-mysql
    tty: true
    environment:
      - MYSQL_DATABASE=api_development
      # - MYSQL_USER=rootuser
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
    ports:
      - "3307:3306"
    volumes:
      - ./mysql/db_data:/var/lib/mysql
